### ISSUE TITLE
Cannot represent matching all files against multiple patterns

### ISSUE THREAD

**Issue by luisrayas3** [actions/labeler#423]
The use-case seems like it would be quite useful and natural: I would like a label to apply if ALL of the changed files are of a few certain types. For example:

```yaml
documentation:
  - all: ["**/*.md", "**/*.puml"]
```

This of course doesn't work as all files need to match both patterns which never happens. Another attempt:

```yaml
documentation:
  - all: ["**/*.md"]
  - all: ["**/*.puml"]
```

This almost works but does not work if the change touches both `md` files and `puml` files.

AFAICT there is no way to represent what I'm trying to do, but it feels like a very natural and useful case to support.

**Comment by ilya-lavrenov** [comment]
Why this does not work?
```
documentation:
  - "**/*.md"
  - "**/*.puml"
```

**Comment by dfandrich** [comment]
My reading of the documentation is that that example is the same as:

```
documentation:
  - any: ["**/*.md"]
  - any: ["**/*.puml"]
```
This would add the *documentation* label to a PR consisting of 99 .c files and one .md file, which is not the intention.

**Comment by dfandrich** [comment]
Just so it's explicitly clear, I have  PR #487 outstanding that adds this feature.

**Comment by silverwind** [comment]
See comment https://github.com/actions/labeler/pull/487#issuecomment-1714030118 which illustrates my idea of how this filter would work.

**Comment by MaksimZhukov** [comment]
Hello everyone!
We've released a new [beta version](https://github.com/actions/labeler/releases/tag/v5.0.0-beta.1) of the action with this feature on board. We would appreciate it if you could use the new version and share with us your feedback.

**Comment by dfandrich** [comment]
That looks like it satisfies this feature nicely! What's not clear from the documentation is what happens when multiple of `AnyGlobToAllFiles`, `AnyGlobToAnyFile` appear in a `changed-files` section. To all of them need to match for the label to be added, or any one of them? Or does the higher-level `any:` or `all:` answer that? It's not clear.

**Comment by MaksimZhukov** [comment]
Hello everyone! 
We have released the [new major version of the action](https://github.com/actions/labeler/releases/tag/v5.0.0) that includes the implementation of this feature. Please read the [action documentation](https://github.com/actions/labeler/tree/main#pull-request-labeler) to find out how to adapt your configuration files and workflows for use with the new action version.

Thank you all for your patience!
Do not hesitate to contact us if you have any questions!

**Comment by jnewb1** [comment]
how would you accomplish this with the new syntax?

all files in the PR must match on of the following globs:
```
'.github/**', '**/test_*', 'Jenkinsfile'
```

I believe this is the same case as the one listed in this issue

my thought would be 
```
CI / testing:
  - all:
    - changed-files:
      - any-glob-to-all-files: ['.github/**', '**/test_*', 'Jenkinsfile']
 ```
 
 but I believe this will fail is you change both ```.github/test``` and ```Jenkinsfile```, since one of the globs will fail

**Comment by dfandrich** [comment]
@jnew1 this is what I would expect for those four patterns you show:

1. match (both files find a pattern that matches)
2. match (test.md matches *.md, and that's all you need)
3. no match (there's no file matching *.puml)
4. no match (test.md doesn't match *.puml)

You wouldn't ever see a configuration like the last two, since they are impossible to ever be true. A more realistic case might be something like `all-glob-to-all-files: ['README*',  '*.txt'] ` where it's possible for a single file to match both patterns.

**Comment by jnewb1** [comment]
unfortunently, the first case doesn't match

```
describe('check my case', () => {
  const changedFiles = ['test.md', 'test.puml'];

  describe('when all given glob patterns matched all files', () => {
    const globPatterns = ['**/*.md', '**/*.puml'];

    it('returns true', () => {
      const result = checkIfAnyGlobMatchesAllFiles(
        changedFiles,
        globPatterns,
        false
      );
      expect(result).toBe(true);
    });
  });
});
```

**Comment by dfandrich** [comment]
The globPatterns in that test match only paths containing at least one slash. `foo.md` won't match `**/*.md`  but `bar/foo.md` will. To also match files in the root of the repo, you need to specify `const globPatterns = ['*.md', '**/*.md', '*.puml', '**/*.puml'];`

**Comment by jnewb1** [comment]
same issue with this test

```
describe('check issue #423', () => {
  const changedFiles = ['test.md', 'test.puml'];

  describe('when at least one pattern matches all files', () => {
    const globPatterns = ['*.md', '*.puml'];

    it('returns true', () => {
      const result = checkIfAnyGlobMatchesAllFiles(
        changedFiles,
        globPatterns,
        false
      );
      expect(result).toBe(true);
    });
  });
});
```

**Comment by dfandrich** [comment]
That test is similar to to the existing checkIfAnyGlobMatchesAllFiles test
but with two different file extensions in changedFiles. I would expect both
tests to pass, unless this matcher is supposed to be "ANY *one* glob must match
against ALL changed files" which doesn't sounds very useful (or intuitive).

**Comment by jnewb1** [comment]
> "ANY *one* glob must match
yes that is exactly what it is

> doesn't sounds very useful (or intuitive).
right

I believe I laid out a solution here: https://github.com/actions/labeler/issues/423#issuecomment-1843946104
I'll look at making a PR for it

**Comment by jnewb1** [comment]
this exact scenario is actually tested for here, so perhaps we just need a new rule:

https://github.com/actions/labeler/blob/8558fd74291d67161a8a78ce36a881fa63b766a9/__tests__/changedFiles.test.ts#L228C3-L239C6

**Comment by dfandrich** [comment]
Looks like you're right. I'd be up for renaming `AnyGlobMatchesAllFiles` to `OneGlobMatchesAllFiles` since that's what it does.  Unless these semantics were used by mistake. I suspect the latter, because the current misnamed `OneGlobMatchesAllFiles` semantics could be implemented without it, in terms of `AllGlobsMatchAllFiles`, like:
```
- any
  - changed-files
    - all-globs-to-all-files: ['glob1']
    - all-globs-to-all-files: ['glob2']
    - all-globs-to-all-files: ['glob3']
```
whereas the reverse is not true. There is no way to implement `AnyGlobMatchesAllFiles` (the real one) in terms of the others.

**Comment by dfandrich** [comment]
FWIW, #731 was opened about the issue we've been discussing in the latter comments.
