### ISSUE TITLE
Labeler removes label that is already set by Dependabot

### ISSUE THREAD

**Issue by efb4f5ff-1298-471a-8973-3d47447115dc** [actions/labeler#442]
This happens on:

- https://github.com/FreeTubeApp/FreeTube/pull/2669
- https://github.com/FreeTubeApp/FreeTube/pull/2670
- https://github.com/FreeTubeApp/FreeTube/pull/2671
- https://github.com/FreeTubeApp/FreeTube/pull/2672

Related files:

- https://github.com/FreeTubeApp/FreeTube/blob/development/.github/workflows/label-pr.yml
- https://github.com/FreeTubeApp/FreeTube/blob/development/.github/labeler.yml
- https://github.com/FreeTubeApp/FreeTube/blob/development/.github/dependabot.yml

Is this a configuration error on my end? The intended purpose of setting the dependencies label through the labeler workflow is when we update a dependency manually instead of using dependabot.

Something to note is that the bot only removes the `dependencies` label and not the `waiting for review` label even though the label is used in both workflows.

**Comment by MaksimZhukov** [comment]
Hello @efb4f5ff-1298-471a-8973-3d47447115dc ! 
Thank you for reporting this!

Unfortunately, there is a [bug](https://github.com/actions/labeler/issues/112#top) in the labeler action and your labels are removed due to it. The `sync-labels` input does not work properly. By default, its value is `true` actually.  In this case, the labeler action will remove the label from the PR if the label globs do not match the files modified in scope of the PR.

Here is a list of possible solutions:
1) Add globs to match files that may be changed by Dependabot
2) Use different labels
3) Use the following workaround until the bug is fixed:
```yml
sync-labels: ''
```
Sorry for the inconvenience!

**Comment by MaksimZhukov** [comment]
I’m closing the issue. Please let us know if you have any concerns.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
Hi @adam-azarchs, how should i configure the workflow after ur pr has been merged to address this issue?

Will the bot remove the label after ur pr has been merged or not?

**Comment by adam-azarchs** [comment]
It will not.  And if you're using the workaround mentioned above, the action will fail until you remove it, which is why it'll be a major version bump.

**Comment by efb4f5ff-1298-471a-8973-3d47447115dc** [comment]
> It will not. And if you're using the workaround mentioned above, the action will fail until you remove it, which is why it'll be a major version bump.

I'll just wait for the next version. We are not using the workaround.
