### ISSUE TITLE
Labeler does not match **/*.[extension]

### ISSUE THREAD

**Issue by alebaffa** [actions/labeler#585]
**Description:**
I am trying to match all markdown files changed in any place in the repository, regardless of the path.
I really tried many different configurations with also older versions, but I don't seem to make it work.
I must be doing some really stupid mistakes, but I cannot figure it out.
Can you kindly help? Thank you!!

**Action version:**
4.1.0

**Platform:**
- [x] Ubuntu
- [ ] macOS
- [ ] Windows

**Runner type:**
- [ ] Hosted
- [x] Self-hosted

**Repro steps:**  
I have created this repo to test my changes: [https://github.com/alebaffa/github-actions-tests](https://github.com/alebaffa/github-actions-tests) .
I have `.github/labeler.yml` with this content:
```bash
documentation:
- '**/*.md' # I also tried with /**/*.md but does not work either
```
and `.github/workflows/labeler.yml` with this content:
```bash
name: "Labeler"
on:
- pull_request_target # also tried - pull_request with types [opened]

jobs:
  pr-labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4.1.0
      with:
        sync-labels: true
```
I change or create md files in the repository and make a PR.
**Expected behavior:**
I expected to have the PR labeled with the `documentation `label.

**Actual behavior:**
The action does not work.

**Comment by alebaffa** [comment]
Just saw #526 . Probably it's the same issue? Though, this case is also mentioned in the examples in the documentation..not sure..

**Comment by bewuethr** [comment]
I observe the same issue. Specifically, with v4.1.0, a change in a top-level `README.md` is not picked up; with v4.0.4, it is (for the configuration shown above). Maybe regression introduced by the `dot` feature?

**Comment by alebaffa** [comment]
I think the comment by @bewuethr, and his [PR](https://github.com/bewuethr/github-actions-tests/pull/1), describes the issue and how to replicate it more clearly than what I wrote. I then tested so many other things, delete branches and merged PRs that now it's difficult to give you something replicable from my repo.
Basically, as bewuethr tested, I am just following the examples given in the documentation with the latest release and the label is not applied.

**Comment by AndreiLobanovich** [comment]
@alebaffa, I have investigated the PR you mentioned. Action works just fine, the issue in the PR is using '/' in the beginning of the blob `/**/*.md`. If you change it to `**/*.md` - it works as expected.


cc @bewuethr

**Comment by bewuethr** [comment]
> @alebaffa, I have investigated the PR you mentioned. Action works just fine, the issue in the PR is using `/` in the beginning of the blob `/**/*.md`. If you change it to `**/*.md` - it works as expected.
> 
> cc @bewuethr

I thought "that's not right" and started more reproducers, based on this config:

```yaml
name: Labeler
on: 
  - pull_request_target

jobs:
  label:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/labeler@v4.0.4
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
```

Then I did this:

1. https://github.com/bewuethr/github-actions-tests/pull/3
2. https://github.com/bewuethr/github-actions-tests/pull/4
3. Update config to v4.1.0
4. https://github.com/bewuethr/github-actions-tests/pull/5
5. https://github.com/bewuethr/github-actions-tests/pull/6

aaaand they all work as expected, so that simple reproducer is wrong.

I definitely noticed a disparity between v4.1.0 and v4.0.4 with `sync-labels: true`, trying to reproduce here:

1. Enabled `sync-labels: true`
2. Opened PR that touched top-level README: https://github.com/bewuethr/github-actions-tests/pull/7
3. Switched back to v4.0.4
4. Switched back to 4.1.0

... but that also all behaved correctly.

The only weird thing I ever observed was in [this PR](https://github.com/bewuethr/github-actions-tests/pull/1), where switching between v4.0.4 and v4.1.0 would add and remove the label:

![image](https://github.com/actions/labeler/assets/8521043/4dfb25c5-04de-4af7-9afa-a322d00af647)

But I haven't been able to reproduce this 🤷🏻‍♂️

**Comment by AndreiLobanovich** [comment]
@bewuethr, thanks for your efforts in reproducing the issue, much appreciated!
@alebaffa, are you still experiencing any difficulties regarding the topic? Is there anything I could help you with?

**Comment by alebaffa** [comment]
Thank you both for your help. I am going to close this issue.
