### ISSUE TITLE
Contributors documentation is incorrect

### ISSUE THREAD

**Issue by ericcornelissen** [actions/labeler#81]
The [docs/contributors.md](https://github.com/actions/labeler/blob/efc1b29f09efe879241e3b11e710d114dc56ef1f/docs/contributors.md) file on the `main` branch is outdated:

- Husky is no longer used by this project
- The runtime dependencies in node_modules should no longer be committed
- The build output folder has been renamed from "lib" to "dist"

I'd be willing to write something up to update the existing text (e.g. based on [the Contributing Guidelines of `actions/cache`](https://github.com/actions/cache/blob/eed9cfe64d00dd64cbb36bec915d41dd6fab9f6c/CONTRIBUTING.md)) but as a outsider I'm not sure if I'm the right person to do that.

**Comment by dakale** [comment]
Thanks for bringing this up. Its definitely an area that needs work. I think theres plenty of things anyone can contribute here. A lot of the contributing docs are just welcoming, encouraging the fork+pr model, etc. Thats something I can drop in as a general representation of how we at GitHub work with the community

There are also project specific details that might warrant including. Some of them you mentioned: what tools are used, what files are committed and how things are structured, and how to build and test (well, that process needs work too). Its fairly tricky because I think the discrepancies are coming from the fact that we migrated a lot of actions from husky->ncc, and have updated the general model that we recommend for building actions (checking in full out including node_modules vs something more webpack-y), but I made that switch for this action as a version change, for safety. So theres a v2 labeler being released from `releases/v2` as to not break existing users, and that has a different set of conventions than the v3+ version that Im releasing from `main` 

Its probably worth focusing most those development details that you mentioned on the new model, so I totally agree with the premise. I dont expect many contributors to have interest in maintaining the "legacy" branch, but that information should probably live *somewhere*, for future maintainers

Definitely something ill think about as time permits!

**Comment by ericcornelissen** [comment]
> Thanks for bringing this up. Its definitely an area that needs work. I think theres plenty of things anyone can contribute here. [...]

In that case I will see if I can get a PR out with some basic improvements :smile: As an aside, any particular reason why this repository is not (or should not) using the more standard(?) `CONTRIBUTING_GUIDELINES.md` file at the root of the repo?


> [...] A lot of the contributing docs are just welcoming, encouraging the fork+pr model, etc. Thats something I can drop in as a general representation of how we at GitHub work with the community

I might be mistaken but _"encouraging the fork+pr model, etc"_ doesn't seem to be there (and I don't remember ever seeing it in this repo). Personally, I still think it is useful to have there _even though_ it is common on GitHub.


> [...] So theres a v2 labeler being released from `releases/v2` as to not break existing users, and that has a different set of conventions than the v3+ version that Im releasing from `main`
>
> Its probably worth focusing most those development details that you mentioned on the new model, so I totally agree with the premise. I dont expect many contributors to have interest in maintaining the "legacy" branch, but that information should probably live somewhere, for future maintainers

That's a good point, though I would imagine that you can keep the guidelines separate for each. My comments only apply to `main`, and, in fact, the guidelines on `releases/v2` seems pretty much fine as is.

**Comment by dakale** [comment]
Fixed by #97
